version: '3.8'

services:
  remote-runner:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    container_name: remote-runner-container
    ports:
      - "8080:8080"
    volumes:
      # Permette al container di comandare l'host tramite il socket di Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mantiene i file del progetto persistenti nella cartella della VM
      - .:/app
    restart: always