services:
  remote-runner:
    build: .
    container_name: remote-runner-container
    user: root
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # Permette di comandare Docker dell'host
      - /var/run/docker.sock:/var/run/docker.sock
      
      # Mappa la cartella attuale per vedere "Progetto-Informatica" fuori
      - .:/app
      
      # CRITICO: Impedisce alla cartella locale di cancellare express dal container
      - /app/node_modules
      
    restart: always
