services:
  remote-runner:
    build: .
    container_name: remote-runner-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Passiamo il comando docker e compose dall'host al container
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
      - .:/app
      - /app/node_modules
    restart: always
